abstract class AppImages {
  static const String logoProsper = "lib/assets/logo_prosper.png";
  static const String fundo = "lib/assets/fundo.png";
  static const String botImg = "lib/assets/bot.png";
  static const String person = "lib/assets/person.png";
  static const String gifProsper = "lib/assets/logo_video.gif";
  static const String illustration1 = "lib/assets/illustration01.png";
  static const String illustration2 = "lib/assets/illustration02.png";
  static const String illustration3 = "lib/assets/illustration03.png";
  static const String googleLogo = "lib/assets/google_icon.png";
  static const String trofeus = "lib/assets/trofeus.png";
  static const String logozinha = "lib/assets/logozinha.png";
  static const String nonotification = "lib/assets/nonotificacao.png";
  static const String comnotification = "lib/assets/comnotificacaon.png";
  static const String whatsapp = "lib/assets/whatsapp.png";
  static const String idCard = "lib/assets/idCard.png";
  static const String circlePen = "lib/assets/circlePen.png";
  static const String penName = "lib/assets/penName.png";
  static const String search = "lib/assets/search.png";
  static const String imgCliente = "lib/assets/imagens_cliente.png";
  static const String comnotificacaonwhite= "lib/assets/comnotificacaoWhite.png";
  static const String graphic_icon = "lib/assets/graphic-icon.png";
  static const String money_icon = "lib/assets/money-icon.png";
  static const String bg_periodButton = "lib/assets/backgroundPeriodButton.png";
  static const String bg_noselectedperiodButton = "lib/assets/noSelectedBgPeriodButton.png";
  static const String add_button = "lib/assets/add-button.png";
  static const String money_icon_customer = "lib/assets/tdesign_money.png";
  static const String customer_image = "lib/assets/imagem_cliente.png";
}
